### PR TITLE
Decode json messages and embed them

### PR DESCRIPTION
**Pull request by sj26**
Love the project. We're trying it out at the moment. Wanted a cleaner way to blat logs at CloudWatch Logs with more context and minimal footprint — this is perfect.

I'm spitting out nginx access logs using a json format like so:

image

I'd like for these to be recognized as a JSON, parsed into an object, and have the object embedded as the "message" instead of just as string. That way I can [do json filtering](http://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html#d0e4022) and use [jmes queries](https://github.com/jorgebastida/awslogs/pull/88) to do cool things(tm).

screenshot 2016-09-16 16 09 12

This is even more neat if you combine it with something like [lograge](https://github.com/roidrage/lograge) with json output for deeply-queryable and aggregatable logs!

### CODE REVIEW

**Comment by apparentlymart** [comment]
Hi @sj26! This is a great idea.

Do you think we could do it without actually parsing and re-serializing the data? I'm a little worried about the additional pressure this might create on the heap if lots of JSON objects of various complexity are being passed through.

What I'm thinking: perhaps we make a `type logMessage string` and then have that alias type implement MarshalJSON something like this:

``` go
func (m logMessage) MarshalJSON() ([]byte, error) {
    if (m != "" && value[0] == "{") {
        // Assume that message is already in JSON format, so
        // we can just emit it directly.
        return []byte(m)
    } else {
        return json.Marshal(string(m))
    }
}
```

This will still create a little heap pressure with the conversion from string to byte, so maybe this is just a wash... not sure if there's a different way to write this such that we avoid that conversion.

The other downside of this approach is that we can't guarantee to always produce valid JSON; if someone emits a log message like `"{ omg something happened }"' then we'd emit that literally in the middle of the JSON object. Honestly not sure if I consider that a big problem... maybe it's just the application's responsibility to not emit garbage?

Honestly not really sure whether I like this alternative path or not. I'm curious to hear what you think... this tool has been written with an _eye_ to keeping memory allocation to a minimum so it's less likely to bloat up and crash/thrash under a high log volume, but we certainly aren't 100% allocation-free in the main loops and we've never done proper memory profiling on it, so maybe we should just accept this extra allocation pressure to get this cool new functionality.

**Comment by sj26** [comment]
It would be nice to avoid too many allocations!

I don't feel comfortable presuming anything starting with an opening brace is JSON because not all logs emitted to syslog on a system are under an operator's control. I'd like to at least scan the string to make sure it looks like JSON.

I went looking for a lightweight way to validate json but couldn't find much.

There's actually a method inside the standard Golang encoding/json package, [checkValid](https://github.com/golang/go/blob/964639cc338db650ccadeafb7424bc8ebb2c0f6c/src/encoding/json/scanner.go#L18-L32), which does a no-allocation pass over JSON data to check if it's valid. I've just extracted a copy into [a package](https://github.com/sj26/golang-x-encoding-json-valid) albeit with a scanner allocation. I'll send a pull request for this upstream as well. Do you think that might do it?

The byte conversion could perhaps be avoided by using [GetDataBytes](https://github.com/coreos/go-systemd/blob/2f344660b11f7285b0af86195c4456e92970f640/sdjournal/journal.go#L595-L604). We could push the journal value retrieval down into the switch.

**Comment by apparentlymart** [comment]
Thanks for investigating this, @sj26!

Using checkValid as an allocation-lite way of detecting this sounds like a great idea. Hopefully that scanner allocation can be detected by [escape analysis](http://blog.rocana.com/golang-escape-analysis) so that it becomes a stack allocation and gets cleaned up immediately after `IsValid` returns, avoiding any heap allocation at all in that path.

Perhaps we can still retain the check for an initial `{` as a "fast path" for stacks where the logs are never JSON; that way we'll avoid the need to scan over the buffer in that case.

The refactoring to be able to use `GetDataBytes` seems like a plausible path to eliminating that string to bytes conversion, albeit probably at the expense of some non-trivial reorganization of the code. It'd be interesting to see how much heap-escaping is already going on in that journald-reading main loop to decide if this is an optimization or a micro-optimization.

**Comment by sj26** [comment]
Submitted `bool json.IsValid([]byte)` upstream to Golang: https://go-review.googlesource.com/#/c/29494/

**Comment by apparentlymart** [comment]
@sj26 it looks like your patch to Go got caught up in their process. Do you think you'll be able to continue along that path yourself based on the feedback from @bradfitz, or would you like some help with that?

**Comment by sj26** [comment]
The golang patch got in!

We found there was too much data in the logs for us to store it cost effectively so we're now using a version which just emits basic log messages. I might close this for now, but it's still a nice idea!

**Comment by apparentlymart** [comment]
Just some book-keeping info to link together the discussions here:

* JSON validity check function proposed in golang/go#18086, and accepted.
* Patch submitted as [CL#34202](https://golang.org/cl/34202) and accepted.

Thanks for proposing that, @sj26! I still like this idea but don't have time to work on it right now, so I'm going to keep this here to remind us of what we discussed.

**Pull request closed without merging**
